### ISSUE TITLE
Positronics Lab dependency needs fix in script

### ISSUE THREAD

**Issue by alexandroid000** [alexandroid000/self-assembly#6]
The following script is used to install the positronicslab dependency:

```
echo "deb http://ppa.launchpad.net/gwu-positronics/ravelin/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list

echo "deb-src http://ppa.launchpad.net/gwu-positronics/ravelin/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list
	sudo apt-get update
	sudo apt-get install ravelin
	pip install awscli
	echo "\nexport PYTHONPATH=$PYTHONPATH:/home/justin/Documents/bouncy/self-assembly/dataAnalysis/src\n" >> ~/.bashrc 
```

And gives the error `pip: command not found`. The path should be changed as well.

**Comment by Jbwasse2** [comment]
Fixed pip dependency. I also got rid of adding that line of "PYTHONPATH" as I do not feel that the "DataAnalysis" folder should depend on installing stuff from the "Gazebo" folder.
